### ISSUE TITLE
Latest Patch for testnet-2 bring a lot of validator nodes to INACTIVE status

### ISSUE THREAD

**Issue by exidz** [KiraCore/kira#112]
After the patch made in testnet-2 a lot of validator nodes become INACTIVE status (reported in telegram) after they update there node (including me). The problem that I found why I slashed is my machine missed a lot of block sequentially but I didn't encounter this issue since the start of testnet-1 and testnet-2.

**Comment by asmodat** [comment]
algorithm will change on the `testnet-3`, this isssue is not related to KIRA Manager (`kira`) but `sekai` repository
