### ISSUE TITLE
priv_sentry node stuck to restart 

### ISSUE THREAD

**Issue by phamhung3589** [KiraCore/kira#130]
When Re-Initialize infrastructure, the network stuck in starting prive_sentry node and the network cannot finish catching up. 
Another problem is the current height of block smaller than the truth heigh -> so the network cannot pass this step. The detail as picture below: 
![Screenshot from 2021-04-08 00-13-24](https://user-images.githubusercontent.com/34591414/113907508-a4aa2200-97ff-11eb-9ada-2c58600e4b0e.png)

**Comment by NormanBB** [comment]
Update  has been released.

Re-Initialize is needed.

**Comment by asmodat** [comment]
should be resolved on the `latest` branch
