### ISSUE TITLE
Installing without supplying / saving public peer

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#149]
When running a clean setup and starting the installer it will ask an ip (advanced mode) , it this phase is not saved it will continue and after the reboot kira will fail as following:

![image](https://user-images.githubusercontent.com/6506666/114082491-193b9a00-98ae-11eb-8d59-e993a0ec60ad.png)

Maybe a condition that at least one successful peer is set/saved ?

**Comment by asmodat** [comment]
could you please provide full console output I am not sure where exactly this can be found in the code

**Comment by Creamers158** [comment]
Sorry, didnt capture more. But first I did the install, then the installer asks to reboot, then I run kira command again to proceed the installation after reboot. Then after some while it gives the above message.

**Comment by asmodat** [comment]
bug was found and resolved on the `latest` banch
