### ISSUE TITLE
Run Kira's unrelated container makes validator INACTIVE

### ISSUE THREAD

**Issue by ilfroloff** [KiraCore/kira#166]
Hi there,

I have interesting issue about using Kira with independent docker containers (they aren't related to Kira). Kira’s manager throws an infrastructure issue with INACTIVE status but a validator works fine (the validator is shown as ACTIVE on https://testnet-rpc.kira.network/api/valopers?all=true at least).

I've run container:
![run](https://i.ibb.co/yFchD65/Screen-Shot-2021-04-16-at-21-08-35.png)

Stopped container:
![run](https://i.ibb.co/M7JvkNg/Screen-Shot-2021-04-16-at-21-10-01.png)

**Comment by asmodat** [comment]
If you introduce non existing container with unknown or unhealthy status it will show as unhealthy infra. I suggest to introduce a health check to your new custom container. Infra shows unhealthy if there is any container that does not have `healthy` staus, does not matter if created by KM or not

**Comment by asmodat** [comment]
Your screenshot is NOT showing INACTIVE status, it shows unhealthy status
