### ISSUE TITLE
minimal block before signing give negative value

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#173]
I deployed using the advance mode to simulate this again.
Followed the regular steps but filled in minimal block height 100  (my validator on this node is not elected so no risk here)

This will result in negative blocks left:
![image](https://user-images.githubusercontent.com/6506666/115142192-b762f900-a040-11eb-8b53-eba108cb9d11.png)

**Comment by asmodat** [comment]
+ instructions are internal instructions (set -x), you are in the discovery mode until node catches up

**Comment by Creamers158** [comment]
![image](https://user-images.githubusercontent.com/6506666/115143238-6524d680-a046-11eb-9ecc-cf995ac9cec4.png)

Provided with a block number higher than current chain height.

It's confusing to see the negative number, but understand what you mean now.

Would be nice to see how much blocks it needs to catch up to.
