### ISSUE TITLE
Seed nodes failed while updating KIRA

### ISSUE THREAD

**Issue by sprprashanth1443** [KiraCore/kira#176]
I tried to update the KIRA tool version using Re-install option and also with command which is provided https://github.com/KiraCore/testnet/blob/main/README.md document. When I restarting the KIRA tool its continuously running at the end showing the error like ERROR: Check validator Node id check failed!
![issue](https://user-images.githubusercontent.com/64004106/115386364-ec18b100-a1f6-11eb-9fd6-3bd47575d9eb.jpg)

**Comment by asmodat** [comment]
resolved in the branch `testnet-3`
