### ISSUE TITLE
latest setup asking confirmation

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#226]
No error, just feedback:

Initial setup before the agreement is asking a confirmation.
Ubuntu 20.04 installed on vm using minimal installation option, updated/upgraded and openssh-server installed.
Nothing more nothing less :)

See image:

![image](https://user-images.githubusercontent.com/6506666/118397245-651ef300-b653-11eb-80ef-187983dec138.png)

After choosing Y it still continues.

**Comment by Creamers158** [comment]
another observation:
![image](https://user-images.githubusercontent.com/6506666/118408700-f9567d80-b686-11eb-9631-cac438d32937.png)

**Comment by asmodat** [comment]
resolved with the latest release
