### ISSUE TITLE
A Small Suggestion

### ISSUE THREAD

**Issue by NormanBB** [KiraCore/kira#227]
I noticed that in kira manager, we need to use lowercase to enter different mode.Using uppercase just keep flashing screen.

```
    if [ "${OPTION,,}" == "d" ]; then
        $KIRA_MANAGER/kira/kira-dump.sh || echoErr "ERROR: Failed logs dump"
        EXECUTED="true"
```

I suggest adding uppercase support to make it more flexible.

**Comment by asmodat** [comment]
"${OPTION,,}" is an upper case support
