### ISSUE TITLE
sentry container does not exists yet

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#230]
Sharing Experience: 

When deploying on a clean server using the v0.3.7.1 it seemed it got stuck several times, see image.
![image](https://user-images.githubusercontent.com/6506666/120065545-1e2cf680-c072-11eb-9a96-27d697ac49b8.png)

A second time the sentry was looking for new blocks. I choose autodiscovery when starting the installation. I left it running a whole night but no new blocks were found.

Starting a clean installation and choosing the minimal installation and adding 20 peers manually from the snaps.txt it worked straight away.

**Comment by asmodat** [comment]
should be resolved with v0.3.7.7 if issue persists you can attempt restarting container in question during setup by force opening KM
