### ISSUE TITLE
INFRASTRUCTURE IS UNHEALTHY

### ISSUE THREAD

**Issue by 8888-droid** [KiraCore/kira#241]
VALIDATOR NODE IS NOT PRODUCING BLOCKS
ISSUES DETECTED, INFRASTRUCTURE IS UNHEALTHY
![2021-06-04_23-11-58](https://user-images.githubusercontent.com/82897300/120857783-78561c00-c58a-11eb-80ac-078f1d647811.png)

**Comment by asmodat** [comment]
This is not a bug report, just a pix
