### ISSUE TITLE
change infrastructure exits setup

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#257]
When starting the setup it will show this menu to change infrastructure mode.
There is no option to "return" back to this validator menu when someone chooses Exit.
Either the exit should not be visible or it should say return to bring the user back to the Change Infrastructure Mode Menu.

See attachments/pictures:
Choose 5:
![changeinfra](https://user-images.githubusercontent.com/6506666/121058621-d409ea80-c7c0-11eb-92a7-589a08aa2658.png)
Wanted to return, but exit showing:
![exit](https://user-images.githubusercontent.com/6506666/121058624-d53b1780-c7c0-11eb-9207-49c93fa9c1d1.png)

**Comment by asmodat** [comment]
Resolved with v0.5.0.3
