### ISSUE TITLE
Menu items shifted

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#259]
One picture shows what I mean.
0 - is not P2P but PORT 22  in the CONFIGURATION MENU v0.4.0.5

![menu swifted](https://user-images.githubusercontent.com/6506666/121075132-1b9a7180-c7d5-11eb-83dc-e70d29492367.png)

I've noticed this when pressing the R to restart networking but it doesnt react to the R .

**Comment by asmodat** [comment]
Resolved with v0.5.0.3
