### ISSUE TITLE
whitelisted but still All ports are open to public message

### ISSUE THREAD

**Issue by Creamers158** [KiraCore/kira#260]
When I whitelist some ports the message is still that I have all ports open to Public.
If I remember correctly in first version this was showing different. Now it feels like the setting is not active.
I restarted and reload the networking part but the text didn't change:

![image](https://user-images.githubusercontent.com/6506666/121077199-a41a1180-c7d7-11eb-8d9c-a358b47b0380.png)

2nd issue. In the HTTP PORT 56660 CONFIGURATION MENU v0.4.0.5 I try to press  R  to reload but nothing happens

**Comment by Creamers158** [comment]
*EDIT
After the Force Custom Configuration it's showing correctly? Or should the [config] show  custom instead of enabled.?

![image](https://user-images.githubusercontent.com/6506666/121077803-5eaa1400-c7d8-11eb-97c1-9045fe7ac728.png)

2nd issue still remains.

**Comment by asmodat** [comment]
Custom configuration is what applies all changes you set to all your individual ports, if you don't set custom then all is enabled or disabled.
