### ISSUE TITLE
Problem:  ERROR: Failed to launch the infrastructure

### ISSUE THREAD

**Issue by HankFit247** [KiraCore/kira#32]
After many builds, wipes and rebuilds, I always end up with the following:

ERROR: Failed to launch the infrastructure

INFO: No containers were found to be attached to sentrynet network
INFO: Containers will NOT be recconected to the 'sentrynet' network

INFO: No containers were found to be attached to servicenet network
INFO: Containers will NOT be recconected to the 'servicenet' network

INFO: No containers were found to be attached to regnet network
INFO: Containers will NOT be recconected to the 'regnet' network

Further:
INFO: Valid repo details were specified, removing /tmp/home/ubuntu/hd-wallet-derive, /home/ubuntu/hd-wallet-derive and starting git pull...
Unhandled exception. System.Exception: CDHelper v0.6.50 failed during execution of hash command.
   at CDHelper.Program.Main(String[] args) in C:\Users\asmodat\Documents\Visual Studio 2017\Projects\CDHelper\CDHelper\Program.cs:line 126
   at CDHelper.Program.<Main>(String[] args)

**Comment by asmodat** [comment]
Issue is now resolved on the `latest` branch
