### ISSUE TITLE
Error: No pubspec.yaml file found.

### ISSUE THREAD

**Issue by HankFit247** [KiraCore/kira#33]
I ran from source:
https://github.com/KiraCore/kira/tree/initial-validator

Step 20/25 : RUN flutter build web
 ---> Running in 363c452da395
Downloading Web SDK...                                              6.4s
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
The command '/bin/sh -c flutter build web' returned a non-zero code: 1

**Comment by asmodat** [comment]
Issue is now resolved on the `latest` branch
