### ISSUE TITLE
Backup chain state failing in loop

### ISSUE THREAD

**Issue by dragonstake** [KiraCore/kira#343]
KM v0.7.3.1  validator mode

Tested 2 options while "B"acking up.

- Delete old snap + Unhalt container
- Preserv old snaps + No unhalt

Expected:
To produce a zip compressed snapshot of the chain at $HOME/snap 

Result:
First case ended in a loop where the content of the /snap folder shows only one file (up to 30Gb aprox) and then restart the validator container and delete that file once after another. No signs of different behaviour after 2h
Second case also looped restarting continously the validator container but not deleting the /snap temp file. After 2h this is the content and uptime status of the containers:

This belongs to the second case:
```bash
root@vmi565239:/home/ubuntu# docker ps -a
CONTAINER ID   IMAGE            COMMAND                  CREATED      STATUS                   PORTS                                                                          NAMES
8ec924d6658f   interx:latest    "sh -c '/bin/bash ${…"   5 days ago   Up 2 hours (healthy)     0.0.0.0:11000->11000/tcp                                                       interx
17a9b120e192   kira:latest      "sh -c '/bin/bash ${…"   5 days ago   Up 2 minutes (healthy)   0.0.0.0:36656->26656/tcp, 0.0.0.0:36657->26657/tcp, 0.0.0.0:36660->26660/tcp   validator
b14f205ed734   registry:2.7.1   "/entrypoint.sh /etc…"   6 days ago   Up 2 hours               5000/tcp                                                                       registry
root@vmi565239:/home/ubuntu# ls snap -lah
total 218G
drwxr-xr-x  2 root   root   4.0K Dec 27 18:07 .
drwxr-xr-x 15 ubuntu ubuntu 4.0K Dec 21 18:33 ..
-rw-------  1 root   root    17G Dec 27 17:35 ziAB3l3M
-rw-------  1 root   root    25G Dec 27 16:44 ziASqDRA
-rw-------  1 root   root    24G Dec 27 17:45 zidPAvY4
-rw-------  1 root   root    18G Dec 27 17:55 zihYQDob
-rw-------  1 root   root    30G Dec 27 16:54 zilGEgKJ
-rw-------  1 root   root    24G Dec 27 17:14 zinM1TER
-rw-------  1 root   root   5.7G Dec 27 18:09 ziTsMwgS
-rw-------  1 root   root    26G Dec 27 17:04 ziu0wycM
-rw-------  1 root   root    24G Dec 27 17:24 ziVABFKw
-rw-------  1 root   root    29G Dec 27 18:06 ziVIFhVP
```
The space used is far more than the original size of .sekaid/data folder
I  have the log dump file. Not sure if this is the right place to upload it. Maybe sensible data inside that file.. Please, Let me know if this topic is of interest or you'd fast close it if not  ;-) I've heard snapshoting have already been advanced for next version.

**Comment by asmodat** [comment]
This happened due to timeout which was limited for snapshots to 10 minutes, resolved with v0.9.0.5 available now on the master branch
