### ISSUE TITLE
nginx service not starting on frontend container

### ISSUE THREAD

**Issue by derfredy** [KiraCore/kira#38]
After succesfully deployment the only issue I found was that the frontend container was unhealthy.

A look at the logs showed that the nginx was not running. Following telegram chat indications from James (thanks!) the container got healthy after inspecting and running:

service nginx start

+ STATUS_NGINX=' * nginx is not running'
++ service nginx status
+ find /common/logs -type f -size +256k -exec truncate --size=128k '{}' +
+ find /self/logs -type f -size +256k -exec truncate --size=128k '{}' +
+ sleep 30
INFO: Healthcheck => START
+ echo 'INFO: Healthcheck => START'
+ '[' -f /common/halt ']'
+ HALT_CHECK=/common/halt

**Comment by alkadeta** [comment]
In my case restart does not work. Logs are below:

+ STATUS_NGINX=' * nginx is not running'
++ service nginx status
+ find /common/logs -type f -size +256k -exec truncate --size=128k '{}' +
+ find /self/logs -type f -size +256k -exec truncate --size=128k '{}' +
+ sleep 30
INFO: Healthcheck => START
+ echo 'INFO: Healthcheck => START'
+ '[' -f /common/halt ']'
+ HALT_CHECK=/common/halt

**Comment by alkadeta** [comment]
ngin seems to be running 
![image](https://user-images.githubusercontent.com/72661026/108519073-5a65f380-72da-11eb-99f4-1752463ce655.png)

**Comment by true-eye** [comment]
> ngin seems to be running
> ![image](https://user-images.githubusercontent.com/72661026/108519073-5a65f380-72da-11eb-99f4-1752463ce655.png)

Did you restart nginx inside the frontend container or on your machine?

**Comment by alkadeta** [comment]
on my machine

**Comment by true-eye** [comment]
> on my machine

Please inspect the frontend container. You can select frontend on kira manager and then select [i] option to inspect.
Then you can restart the nginx inside the container
```
sudo service nginx restart
```

**Comment by alkadeta** [comment]
Thank youı this solves the issue, my bad
![kiraa](https://user-images.githubusercontent.com/72661026/108519993-3ce55980-72db-11eb-90c6-5ecca41fe080.png)

**Comment by true-eye** [comment]
> Thank youı this solves the issue, my bad
> ![kiraa](https://user-images.githubusercontent.com/72661026/108519993-3ce55980-72db-11eb-90c6-5ecca41fe080.png)

Sounds good. :)

**Comment by donperenjon87** [comment]
I have met many people with a problem with the 5th container

**Comment by true-eye** [comment]
> I have met many people with a problem with the 5th container

Yes. I'm working on it to fix this issue on the script side.

**Comment by true-eye** [comment]
The hotfix is implemented in master branch. I'm closing this. Thanks, guys
