### ISSUE TITLE
Can not restart containers after a [S] STOP All Containers

### ISSUE THREAD

**Issue by derfredy** [KiraCore/kira#40]
If you use option [S] you will get this "exited" containers scenario:

![image](https://user-images.githubusercontent.com/23276270/108605357-e8fa7380-73b3-11eb-9811-a1edb53e7d62.png)

If you use the [R] option to restart them there is an error related to one of the networks. It says the network does not exist and the containers can not be started. So you can not recover after a Stop.

Full log here:

https://pastebin.ubuntu.com/p/WJmRR9nHTt/

**Comment by true-eye** [comment]
Thanks for the report, I think `restart` means re-start. So if it's not started already, we can't restart.
We need to turn the 'RESTART All containers' into 'Start All containers' when it has existed. I will check this `start` feature.

**Comment by asmodat** [comment]
Resolved with latest release, disabled restart option and successful start after stop is now possible
