### ISSUE TITLE
Catching up status turns False after joining a network

### ISSUE THREAD

**Issue by alkadeta** [KiraCore/kira#45]
When I try to join an outside network 

it starts okay with: `INFO: Minimum height: 41633, current height: 39417, catching up: true
INFO: Do NOT close your terminal, waiting for sentry to finish catching up...` 

then it becames 

`INFO: Minimum height: 41633, current height: 39417, catching up: false
INFO: Do NOT close your terminal, waiting for sentry to finish catching up...` 

catching up true turns to false after the first try and loops like this for eternity. 
When I try to restart it Kira gives me unhealthy errors, If I do [I] option, it still gives me the exact same loop.

**Comment by true-eye** [comment]
@alkadeta Could you give me the outside network address you tried to join, please?

**Comment by alkadeta** [comment]
Sure. 62.36.30.20

**Comment by asmodat** [comment]
this is tendermint layer not kira layer, sometimes bloc sync can continue despite syncing flag not being set to `true`
