### ISSUE TITLE
Typo in seeds-edit.sh

### ISSUE THREAD

**Issue by andrsj** [KiraCore/kira#519]
https://github.com/KiraCore/kira/blob/master/workstation/kira/seeds-edit.sh#L270

Instead of `$files` seems to be a `$FILE`, `$files` is not defined in this script and it's not a glob variable:

![image](https://github.com/KiraCore/kira/assets/61803449/b895b644-2687-4087-be03-e3a3226db08d)
![image](https://github.com/KiraCore/kira/assets/61803449/cdccd1e9-b41d-4330-94c4-188827d2f79c)

**Comment by MrLutik** [comment]
@andrsj please check if resolved
