### ISSUE TITLE
Installation | Recurring NetworkManager.service not found | Could lead to incorrect interpretation

### ISSUE THREAD

**Issue by WayneWayner** [KiraCore/kira#68]
During the installation of the Validator Mode in the phase after the reboot, the user will see this recurring message again and again. 

```
+ systemctl restart NetworkManager docker
Failed to restart NetworkManager.service: Unit NetworkManager.service not found.
```
This gives the impression that the installation is caught in an infinite loop and could lead to the user deciding to abort. However, the installation manages to continue on its own after a while, so it would have been wrong to abort here.

Side note: The issue was seen earlier by @darkestH0ur in Telegram.

**Comment by hoanghiepluc** [comment]
Me too

**Comment by asmodat** [comment]
Error message has been changed
