### ISSUE TITLE
Temporary failure in name resolution || Can't docker push the repository (base image) in some VPS provider (e.g. contabo)

### ISSUE THREAD

**Issue by exidz** [KiraCore/kira#75]
I encountered an issue in setting up a validator node in VPS (contabo) when the docker push the base image ↓↓↓
` The push refers to repository [registry.regnet.local:5000/base-image]`
`Get https://registry.regnet.local:5000/v2/: dial tcp: lookup registry.regnet.local: Temporary failure in name resolution`

That issue has a simple fix, by adding a nameserver in the /etc/resolv.conf
`nameserver registry.regnet.local`
`nameserver registry.regnet.local:5000`

Recommendation : Add a command in the script that add nameserver in the /etc/resolv.conf

**Comment by exidz** [comment]
Testnet-2 resolved this issue and working fine with my fresh install ubuntu vps.
Good job team

**Comment by NormanBB** [comment]
Stil don't work in my end. I am using Linode.My local machine has this issue too.

But thanks to you solution.

**Comment by exidz** [comment]
> Stil don't work in my end. I am using Linode.My local machine has this issue too.
> 
> But thanks to you solution.

I still encountered this error in my vps and found out that the resolv.conf will overwitten again to default. So i tried to include the registry.regnet.local:5000 and registry.regnet.local in hosts via this format :
`127.0.1.1      registry.regnet.local      registry.regnet.local:5000`

**Comment by NormanBB** [comment]
> > Stil don't work in my end. I am using Linode.My local machine has this issue too.
> > But thanks to you solution.
> 
> I still encountered this error in my vps and found out that the resolv.conf will overwitten again to default. So i tried to include the registry.regnet.local:5000 and registry.regnet.local in hosts via this format :
> `127.0.1.1 registry.regnet.local registry.regnet.local:5000`

Maybe you mean `127.0.0.1` instead of `127.0.1.1`? I wonder if you config work for you?

The way I used to change config is in this link.

[https://www.tecmint.com/set-permanent-dns-nameservers-in-ubuntu-debian/](url)

After i fixed this error,one thing i need to do is wait for update to be publised so that i can continue my initialization. Yep, slow progress and I don't have a running Kira.
