### ISSUE TITLE
Private and Public sentries are named incorrectly

### ISSUE THREAD

**Issue by derfredy** [KiraCore/kira#76]
If you have a look to the deployment you will see how your private_sentry container is the first trying to connect other nodes.

```
+ sleep 30
+ :
+ echoInfo 'INFO: Awaiting node status...'
+ echo -e '\e[0m\e[36;1mINFO: Awaiting node status...\e[0m'
INFO: Awaiting node status...
+ i=1
++ docker exec -i priv_sentry sekaid status
++ jq -rc .
+ STATUS='{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"16264a156be3c4a68a2deccd95c8aad992ed85bf","listen_addr":"tcp://192.168.122.142:36656","network":"testnet-1","version":"","channels":"40202122233038606100","moniker":"KIRA PRIV_SENTRY NODE","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26657"}},"SyncInfo":{"latest_block_hash":"8778EB26280141B6A5ABA3A097038675A721C73F23D573787B04E71DF778168E","latest_app_hash":"1C4AE6DDD737778AD15FB06DB57A721DD3CB9111C303384F54279E3FF7A6DEBF","latest_block_height":"24388","latest_block_time":"2021-03-31T07:23:09.243782873Z","earliest_block_hash":"6FDE36B63372896061D92E66079C07A355A78F0154205EE3B4032F7FD563AF30","earliest_app_hash":"E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855","earliest_block_height":"1","earliest_block_time":"2021-03-29T19:40:53.392736076Z","catching_up":false},"ValidatorInfo":{"Address":"8F9E8B22D6D6CEA887776062ED6DF288BF987959","PubKey":{"type":"tendermint/PubKeyEd25519","value":"1HuvRvku+8aAt0Qol9XsiWIDk5onkrRYgc5+0UsayNQ="},"VotingPower":"0"}}'
```

After a succesfully deployment you see that your public_sentry is connected only to 2 peers (your validator and your priv_sentry) meanwhile your priv_sentry is connected to much more external peers:

The following image is the "supposed" public sentry

![image](https://user-images.githubusercontent.com/23276270/113282636-7bf9c800-92e7-11eb-9ab8-c3f2bdf5fb0f.png)

The following image is the "supposed" private sentry

![image](https://user-images.githubusercontent.com/23276270/113282794-b6636500-92e7-11eb-8f6e-3aab5038785e.png)

**Comment by asmodat** [comment]
This is a correct behaviour for a validator mode, priv_sentry connects with public networks announcing it's local-ip, this way even if priv_sentry node-id is stored by the public seed no one else connecting to that public seed will know real location of the validator

**Comment by derfredy** [comment]
Thanks for your explanation Asmodat.
I think I understand why the priv-sentry starts the connection. It is because it has a private IP, so you mean we are gossiping that IP instead our real one. All right.
I could agree that is a good strategy to avoid our public IP to be announced.

What I find difficult to agree is that when the infra is up and running we name "private sentry" to the one connected to the world and "public sentry" to the one only connected to our validator. It is totally the opposite of what we do with the rest of tendermint networks and their config.toml    I am afraid that this is only confusing for Tendermint OGs  :-)

Please feel free to close this. I'd like one more little explanation to the second part though, if you please.

**Comment by asmodat** [comment]
`I think I understand why the priv-sentry starts the connection. It is because it has a private IP, so you mean we are gossiping that IP instead our real on`

Correct

`What I find difficult to agree is that when the infra is up and running we name "private sentry" to the one connected to the world and "public sentry" to the one only connected to our validator.`

That sentry should be connected to a private seed node in production you would not be connecting directly to the public networks. That's why manager has 2 modes -> sentry & validator. After first connection is made you can reconfigure the networking using network manager
