### ISSUE TITLE
Most of the docker containers show unhealthy status

### ISSUE THREAD

**Issue by DenysOf** [KiraCore/kira#77]
-----------------------------------------------| [health]
| [0] | Manage registry    : running            : 
| [1] | Manage priv_sentry : running : 49796    : unhealthy
| [2] | Manage sentry      : running : 49796    : unhealthy
| [3] | Manage interx      : running : 49796    : unhealthy
| [4] | Manage frontend    : running            : unhealthy
| [5] | Manage validator   : running : 49796    : unhealthy
| [6] | Manage snapshot    : done               : healthy

Stuck at 49797, logs attached

[kira.zip](https://github.com/KiraCore/kira/files/6249246/kira.zip)

**Comment by asmodat** [comment]
resolved with `testnet-2`
