### ISSUE TITLE
Container blocks stuck at 49999 since 09.52 (UTC+0)

### ISSUE THREAD

**Issue by alkadeta** [KiraCore/kira#79]
Container blocks stuck at 49999, the validator could't validate more blocks since 09:52 utc time
 `2021-04-02T09:52:41.531050745Z`  ERROR: 2021/04/02 09:52:41 [rpc-call] Block not found: 49999`
All the containers show unhealthy status and restarting is not helping.
Logs have been attached.
[kira.zip](https://github.com/KiraCore/kira/files/6249483/kira.zip)
![Untitled](https://user-images.githubusercontent.com/72661026/113415307-973c0480-93c7-11eb-876b-9b1cdbad40b7.png)

**Comment by westaking** [comment]
`10:06PM INF ABCI Handshake App Info hash=71CED9B06A95E435E8B3C88AA6E3559E305FAFBDC3D115DE5F75C4975C4EF513 height=49998 module=consensus protocol-version=0 software-version=
10:06PM INF ABCI Replay Blocks appHeight=49998 module=consensus stateHeight=49998 storeHeight=49999
10:06PM INF Replay last block using real app module=consensus
10:06PM INF Absent validator kiravalcons1aw4g5x4ya33k4ce52smv9yd4r9mmqm2meupn8y at height 49999, 51 mischance, 3158 missed blocks, 3264 produced blocks, threshold 50 module=x/customslashing
10:06PM INF Validator kiravalcons1aw4g5x4ya33k4ce52smv9yd4r9mmqm2meupn8y past min height of 40191 and below signed blocks threshold of 50 module=x/customslashing
10:06PM INF Executed block height=49999 invalidTxs=0 module=consensus validTxs=0
10:06PM INF Updates to validators module=consensus updates=EBAA8A1AA4EC636AE3345436C291B51977B06D5B:0,31140F76FC42E1A7A1711ACE5D268FE2A73DDE81:1,D4EC26408087B77E8D307DAE9EE45F080A6152D5:1,5729EFBB585174D35B2651423053F71396A8AAD5:1,492FFC1E95C6ECD94FA45C4936934D286445056A:1,8482AB39BDA9AF0CB2AADD8DDD382BDDE1800F17:1,EE60368B7AE1EC97D27AF22D4F4E03D2F4B77726:1,F7D045ED1B03FC63B3C3E665B93E926BC98507AF:1,7AEF92A8D5BEB560F541B386CF659504D5386EB1:1,69471AA0DBC1B27405F112E26A2AE9E34A2951B2:1,27CD156FF3493A5AF88A9C626EADE6C1B34082CF:1,EBAA8A1AA4EC636AE3345436C291B51977B06D5B:1
Error: error during handshake: error on replay: commit failed for application: error changing validator set: duplicate entry Validator{EBAA8A1AA4EC636AE3345436C291B51977B06D5B PubKeyEd25519{6DDCB539FEC02B209DC7FAB0F2670CF3FEA7564BE58181A495013D5BB6B7427B} VP:1 A:0} in [Validator{27CD156FF3493A5AF88A9C626EADE6C1B34082CF PubKeyEd25519{10BBF3CAE594EE09C0C5DC14F9C812557BBBEBFAA42446CF9EFBD6DABC0AE3B1} VP:1 A:0} Validator{31140F76FC42E1A7A1711ACE5D268FE2A73DDE81 PubKeyEd25519{F7147BF2372E764A27642D698C81CBE7B6D364A1FE704BB3A63BF08FFC175D7D} VP:1 A:0} Validator{492FFC1E95C6ECD94FA45C4936934D286445056A PubKeyEd25519{539715FAD6BBD4FADE49AC70DFA424E251EAD06CBC85FC07C79C4423823AB2C7} VP:1 A:0} Validator{5729EFBB585174D35B2651423053F71396A8AAD5 PubKeyEd25519{A549CB832960BEABFC42A8DD5A6660CB3B4C4BF5D96E330B2F5D8CD886695DD3} VP:1 A:0} Validator{69471AA0DBC1B27405F112E26A2AE9E34A2951B2 PubKeyEd25519{B7A316A33B885438DD828A82CB53CF3AB52DCFC5F4F78AF77EEE79B7A2B7DBF8} VP:1 A:0} Validator{7AEF92A8D5BEB560F541B386CF659504D5386EB1 PubKeyEd25519{B7AFB13FC0E6A0D9FCC0B15141FDF5C0D66BBE1E3C30D5FA659B4631F266825F} VP:1 A:0} Validator{8482AB39BDA9AF0CB2AADD8DDD382BDDE1800F17 PubKeyEd25519{85A78754C5E9DEC4CE8DD65B79205D0757BF7C885508F03AFE16A04514E7DB65} VP:1 A:0} Validator{D4EC26408087B77E8D307DAE9EE45F080A6152D5 PubKeyEd25519{D0AC6AE1081AD29C64E90F347AE783FCD14857FCE25083860CF8E29ED4649250} VP:1 A:0} Validator{EBAA8A1AA4EC636AE3345436C291B51977B06D5B PubKeyEd25519{6DDCB539FEC02B209DC7FAB0F2670CF3FEA7564BE58181A495013D5BB6B7427B} VP:0 A:0} Validator{EBAA8A1AA4EC636AE3345436C291B51977B06D5B PubKeyEd25519{6DDCB539FEC02B209DC7FAB0F2670CF3FEA7564BE58181A495013D5BB6B7427B} VP:1 A:0} Validator{EE60368B7AE1EC97D27AF22D4F4E03D2F4B77726 PubKeyEd25519{680CEEE5567D9DF73245A3D547AB622D835767FA8C301C0F26580901C512740D} VP:1 A:0} Validator{F7D045ED1B03FC63B3C3E665B93E926BC98507AF PubKeyEd25519{60CA6836A2F01CD79EF469A8ED9618DFA1E70E11B477D88107C2820C5C0C6899} VP:1 A:0}]`

**Comment by asmodat** [comment]
Resolved with `testnet-2`
