### ISSUE TITLE
Infrastructure is unhealthy and stuck at block 49999

### ISSUE THREAD

**Issue by liray-unendlich** [KiraCore/kira#80]
I setup my validator with cleaned dedicated VPS.
Suddenly the validator stopped validating or syncing more blocks since block 49999.

And all services(like priv_sentry, sentry, interx, frontend, validator) are unhealthy.

I attached all logs with this issue.
[kira.zip](https://github.com/KiraCore/kira/files/6249956/kira.zip)

![image](https://user-images.githubusercontent.com/15893314/113424231-c031b900-940a-11eb-8f01-c3ad9a0b9626.png)

**Comment by asmodat** [comment]
Resolved with `testnet-2`
