### ISSUE TITLE
Snapshot monitoring high CPU consumption

### ISSUE THREAD

**Issue by bsrinivas8687** [KiraCore/kira#81]
Frequent snapshot monitoring and checksum calculation is causing the high CPU usage even if all the containers are stopped.

https://github.com/KiraCore/kira/blob/3d7ca18f67c7344a23072549f3ae79af7c1c1bd1/workstation/kira/monitor-snapshot.sh#L51
https://github.com/KiraCore/kira/blob/3d7ca18f67c7344a23072549f3ae79af7c1c1bd1/workstation/kira/monitor-snapshot.sh#L52

**Comment by asmodat** [comment]
should be resolved with `testnet-2`
