### ISSUE TITLE
Never received 'waiting' status and infrastructure is unhealthy

### ISSUE THREAD

**Issue by danenright** [KiraCore/kira#93]
I never managed to reach 'waiting' status with the validator node, also the pub. ip was never displayed.

<img width="812" alt="Screen Shot 2021-04-03 at 2 16 28 pm" src="https://user-images.githubusercontent.com/2581435/113466406-4390f000-9487-11eb-97c4-7a112d6cefa5.png">

**Comment by asmodat** [comment]
testnet-1 was replaced by testnet-2
