### ISSUE TITLE
High disk consumption

### ISSUE THREAD

**Issue by derfredy** [KiraCore/kira#95]
After the first 10h of the testnet I think that some participants could run out of space.
We are in around 0,7G / hour consumption at the start of the network (maybe higher cos snapshots and DB initialization). It got stabilized to 0.42G / hour after this.
I wonder if we could add a hard pruning strategy to all the containers.

Minor changes suggestion:
Add
``` 
--pruning=everything 
```
to this line: 
https://github.com/KiraCore/kira/blob/a511451ef8ef4ad082a041e82cee2cad2c698404/docker/kira/container/validator/start.sh#L137
and here:
https://github.com/KiraCore/kira/blob/a511451ef8ef4ad082a041e82cee2cad2c698404/docker/kira/container/sentry/start.sh#L110

![image](https://user-images.githubusercontent.com/23276270/113490016-eb2e1280-94c7-11eb-8c53-acddc30a5a59.png)

**Comment by asmodat** [comment]
Thank you, added pruning to branch `asmodat3`, tesntet branches will be updated shortly
